Title workar
JelenadlS/quiz-app pull request #7
Opened 2022-01-22 21:28 UTC by JelenadlS

2022-01-22 22:08 UTC, ttaannjjaa requested changes
Awesome work 😁 - i like it very much and i am learning a lot

2022-01-22 22:08 UTC, ttaannjjaa commented on styles/base.css
> +
according to the following code - as i have understood going with bem would mean to give also `details` and `summary` a class name to address them

2022-01-22 22:08 UTC, ttaannjjaa commented on styles/base.css
> +details > summary::-webkit-details-marker {
wow - very cool thing - didn't see this before 👍😅

2022-01-22 22:08 UTC, ttaannjjaa commented on styles/components/app-grid.css
> +.app-grid__fixed-top {
👍 this code meets my thoughts about what's still to do and how to do best

2022-01-22 22:08 UTC, ttaannjjaa commented on styles/components/card.css
> +.card__bookmark:focus {
Cool

2022-01-23 07:02 UTC, JelenadlS commented
> Awesome work 😁 - i like it very much and i am learning a lot

2022-01-23 07:03 UTC, JelenadlS reviewed
Thank you Tanja for the quick check 😊

2022-01-23 07:03 UTC, JelenadlS commented on styles/base.css
> +
yeah you are right, thank you 😊

2022-01-23 07:03 UTC, JelenadlS commented on styles/base.css
> +details > summary::-webkit-details-marker {
haha i found it in the internet - when i now check it, nothing is changing by taking it out. so it is out again, as it seems that i fixed it somehow else 😅 🙈

2022-01-23 07:11 UTC, merged